import type { Metadata } from "next";
import { Cormorant_Upright } from 'next/font/google';
import "../styles/main.scss";

const cormorant = Cormorant_Upright({
  subsets: ["latin"] ,
  weight: "400",
  variable: '--font-cormorant',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cormorant.className}>
      <body>{children}</body>
    </html>
  );
}
